FROM ollama/ollama:latest
# For INTEL/AMD GPUs use ollama/ollama:rocm


COPY Modelfile.analyst /Modelfile
COPY run_models.sh /run_models.sh

RUN chmod +x /run_models.sh

ENTRYPOINT ["/run_models.sh"]
